#Clean errors ***
server:
  error:
    include-stacktrace: on_param

#Docker Connection DB

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rabbitmq
    username: postgres
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG



  rabbitmq:
    addresses: amqps://emupdjgx:qLbniaK4b1HSOiuqFjwpOazwlrx4AvUH@cattle.rmq2.cloudamqp.com/emupdjgx
    queue: rabbitmq
